name: run_script
on:
  push:
  schedule:
    - cron: "* */1 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script
        env:
          SWITCHBOT_TOKEN: ${{ secrets.SWITCHBOT_TOKEN }}
          SECRET: ${{ secrets.SECRET }}
          DEVICE: ${{ secrets.DEVICE }}
          CITY_CODE: ${{ secrets.CITY_CODE }}
        run: |
          python -m switchbotLED
